### ISSUE TITLE
Empty share

### ISSUE THREAD

**Issue by RedGlow** [YunoHost-Apps/UMS_ynh#42]
### Describe the bug

Hello! I'm trying to use this package on my yunohost installation, but it seems that no file is shared and that there are some errors on the logs. I'm not sure whether this is an UMS problem or a problem specific to this package.

### Context

- Hardware: Raspberry Pi 4
- YunoHost version: 11.0.9.9
- I have access to my server: Through SSH, through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no 
  - If yes, please explain:
- Using, or trying to install package version/branch: Universal Media Server v. 11.3.0~ynh1

### Steps to reproduce + Expected behavior

I just installed the package and expected to access my multimedia share directory from vlc installed on my tablet. The share directory was instead empty.

### Logs

https://paste.yunohost.org/xuwalureyo

I think the relevant lines could be:

```
ERROR 14:16:41.081 [pool-4-thread-1] Error initializing process: Cannot run program "ping": error=1, Operation not permitted
WARN  14:16:41.082 [pool-4-thread-1] Error measuring network throughput : Cannot invoke "java.util.List.iterator()" because "ls" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "ls" is null
	at net.pms.network.SpeedStats$MeasureSpeed.doPing(SpeedStats.java:190)
	at net.pms.network.SpeedStats$MeasureSpeed.doCall(SpeedStats.java:146)
	at net.pms.network.SpeedStats$MeasureSpeed.call(SpeedStats.java:105)
	at net.pms.network.SpeedStats$MeasureSpeed.call(SpeedStats.java:93)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Krakinou** [comment]
Hello,
The log seems quite normal, I've the same on my server and it's working.
Also, for the first start, it need a little while to scan all the directories, specifically if you have a lot of files in it (like for me, one good hour before I could see the file for approx 30GB).

If this doesn't solve the issue, can you check what are the value for `folders` and `folders_monitored` in `/home/yunohost.app/ums/.config/UMS/UMS.conf`?


-------- Message d'origine --------
De : Mattia Belletti ***@***.***>
Date : 11/10/2022 14:18 (GMT+01:00)
À : YunoHost-Apps/UMS_ynh ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [YunoHost-Apps/UMS_ynh] Empty share (Issue #42)


Describe the bug

Hello! I'm trying to use this package on my yunohost installation, but it seems that no file is shared and that there are some errors on the logs. I'm not sure whether this is an UMS problem or a problem specific to this package.

Context

  *   Hardware: Raspberry Pi 4
  *   YunoHost version: 11.0.9.9
  *   I have access to my server: Through SSH, through the webadmin
  *   Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
     *   If yes, please explain:
  *   Using, or trying to install package version/branch: Universal Media Server v. 11.3.0~ynh1

Steps to reproduce + Expected behavior

I just installed the package and expected to access my multimedia share directory from vlc installed on my tablet. The share directory was instead empty.

Logs

https://paste.yunohost.org/xuwalureyo

I think the relevant lines could be:

ERROR 14:16:41.081 [pool-4-thread-1] Error initializing process: Cannot run program "ping": error=1, Operation not permitted
WARN  14:16:41.082 [pool-4-thread-1] Error measuring network throughput : Cannot invoke "java.util.List.iterator()" because "ls" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "ls" is null
        at net.pms.network.SpeedStats$MeasureSpeed.doPing(SpeedStats.java:190)
        at net.pms.network.SpeedStats$MeasureSpeed.doCall(SpeedStats.java:146)
        at net.pms.network.SpeedStats$MeasureSpeed.call(SpeedStats.java:105)
        at net.pms.network.SpeedStats$MeasureSpeed.call(SpeedStats.java:93)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
